// Client helpers for the Domain Analysis feature: a ROI-ranked set of use cases
// plus a data-gap analysis for a whole domain (all its products), generated by
// the LLM (grounded in the domain's products/DDL/KPIs) and persisted in Lakebase.
// Mirrors the ontologyArtifact.ts / ontologyOverrides.ts pattern: generate → POST
// → persist server-side → fetch back → regenerate when the input signature drifts.
import type { CatalogProduct } from './deriveComponents';

export type RoiTier = 'High' | 'Medium' | 'Low';
export type GapSeverity = 'Critical' | 'Important' | 'Nice-to-have';

export type UseCase = {
  title: string;
  roi_tier: RoiTier;
  // composite opportunity score 0-100 (weighs ROI tier, data readiness, effort);
  // a sortable numeric call-out since we have DDLs/metadata, not live financials.
  opportunity_score: number;
  // illustrative annual revenue/impact potential in $K (industry benchmark, not
  // derived from this data — labeled as such in the UI).
  revenue_potential_k?: number;
  value_driver: string;
  data_readiness: string;
  effort: string;
  time_to_value: string;
  products: string[];
  tables: string[];
  description: string;
};

export type DataGap = {
  gap: string;
  why_it_matters: string;
  severity: GapSeverity;
  unblocks: string[];
};

export type DomainAnalysis = {
  domain: string;
  domain_label: string;
  llm_used: boolean;
  flagship: { use_case: string; rationale: string };
  use_cases: UseCase[];
  data_gaps: DataGap[];
};

// The product metadata the server prompt is grounded in.
export type AnalysisProduct = {
  product_name: string;
  display_name?: string;
  business_outcome?: string;
  kpis?: string[];
  fact_tables?: string[];
  dim_tables?: string[];
  issue?: string;
  action_hint?: string;
};

// Map a catalog product to the analysis input shape.
export function toAnalysisProduct(p: CatalogProduct): AnalysisProduct {
  return {
    product_name: p.product_name,
    display_name: p.display_name,
    business_outcome: p.business_outcome,
    kpis: p.kpis,
    fact_tables: p.fact_tables,
    dim_tables: p.dim_tables,
  };
}

// Lightweight staleness signature: the set of products (+ their KPIs) that fed
// the analysis. If the domain's product set changes, the stored analysis is stale.
export function analysisSignature(products: AnalysisProduct[]): string {
  const parts = products
    .map((p) => `${p.product_name}:${(p.kpis ?? []).slice().sort().join(',')}`)
    .sort();
  return JSON.stringify(parts);
}

export type DomainAnalysisResult = {
  ok: boolean;
  analysis?: DomainAnalysis;
  llm_used?: boolean;
  persist_warning?: string;
  error?: string;
};

export async function generateDomainAnalysis(args: {
  schema_label: string;
  domain_name: string;
  domain_label: string;
  signature: string;
  products: AnalysisProduct[];
  components_summary?: string;
}): Promise<DomainAnalysisResult> {
  try {
    const resp = await fetch('/api/domain-analysis', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(args),
    });
    return (await resp.json()) as DomainAnalysisResult;
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

export type StoredDomainAnalysis = {
  analysis: DomainAnalysis | null;
  signature?: string;
  llm_used?: boolean;
  generated_by?: string;
  generated_at?: string;
};

export async function fetchDomainAnalysis(
  schemaLabel: string,
  domainName: string
): Promise<StoredDomainAnalysis> {
  try {
    const resp = await fetch(
      `/api/domain-analysis?schema=${encodeURIComponent(schemaLabel)}&domain=${encodeURIComponent(domainName)}`
    );
    return (await resp.json()) as StoredDomainAnalysis;
  } catch {
    return { analysis: null };
  }
}
