// Domain Analysis — a ROI-ranked set of use cases + a data-gap analysis for the
// SELECTED domain (all its products). Generated by the LLM (grounded in the
// domain's products/DDL/KPIs, with a deterministic fallback), persisted in
// Lakebase, and loaded back; regenerable with a staleness indicator. Scope comes
// from the left-panel Domain selection (ALL domains → whole catalog).
import { useState } from 'react';
import { useNavigate } from 'react-router';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  Badge,
  Button,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@databricks/appkit-ui/react';
import { Sparkles, Loader2, AlertTriangle, Star, ArrowRight, RefreshCw, Info, Package, Check } from 'lucide-react';
import { useProduct } from '../lib/product';
import type { RoiTier, GapSeverity, UseCase } from '../lib/domainAnalysis';

const ROI_BADGE: Record<RoiTier, string> = {
  High: 'bg-emerald-600 text-white',
  Medium: 'bg-amber-500 text-white',
  Low: 'bg-muted text-muted-foreground',
};
const SEV_BADGE: Record<GapSeverity, 'destructive' | 'default' | 'outline'> = {
  Critical: 'destructive',
  Important: 'default',
  'Nice-to-have': 'outline',
};

// Resolve a display score. Analyses generated before opportunity_score existed
// (or an LLM that omitted it) persist 0/undefined; derive a sensible value from
// the ROI tier so the column is never a flat 0.
function displayScore(u: UseCase): number {
  const s = Number(u.opportunity_score);
  if (Number.isFinite(s) && s > 0) return Math.round(s);
  return u.roi_tier === 'High' ? 75 : u.roi_tier === 'Low' ? 30 : 50;
}

export function DomainAnalysis() {
  const {
    domainAnalysis,
    domainAnalysisStale,
    domainAnalyzing,
    domainAnalysisLabel,
    regenerateDomainAnalysis,
    describeUseCaseAsProduct,
    useCaseDrafts,
  } = useProduct();
  const navigate = useNavigate();
  const [note, setNote] = useState<string | null>(null);
  const [describingTitle, setDescribingTitle] = useState<string | null>(null);

  // titles that already have a draft (so the button reads "View draft")
  const draftedTitles = new Set(useCaseDrafts.map((d) => d.use_case_title));

  const describe = async (uc: UseCase) => {
    setNote(null);
    setDescribingTitle(uc.title);
    const r = await describeUseCaseAsProduct(uc);
    setDescribingTitle(null);
    if (!r.ok) setNote(`Could not describe "${uc.title}": ${r.error ?? 'unknown error'}`);
    else void navigate('/data-product-drafts');
  };

  const run = async () => {
    setNote(null);
    const r = await regenerateDomainAnalysis();
    if (!r.ok) setNote(`Generation failed: ${r.error ?? 'unknown error'}`);
    else if (r.persist_warning) setNote(`Generated, but not persisted: ${r.persist_warning}`);
  };

  return (
    <div className="space-y-4">
      <Card className="shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between gap-4">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" /> Domain Analysis — {domainAnalysisLabel}
            </CardTitle>
            <CardDescription>
              ROI-ranked use cases and a data-gap analysis across all products in this domain,
              grounded in the schema and enriched with domain expertise.
            </CardDescription>
          </div>
          <Button size="sm" className="gap-1.5 shrink-0" disabled={domainAnalyzing} onClick={() => void run()}>
            {domainAnalyzing ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : domainAnalysis ? (
              <RefreshCw className="h-4 w-4" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            {domainAnalysis ? 'Regenerate' : 'Generate analysis'}
          </Button>
        </CardHeader>
        <CardContent className="space-y-2">
          {note && <p className="text-sm text-destructive">{note}</p>}
          {domainAnalysis && domainAnalysisStale && (
            <div className="flex items-center gap-1.5 text-xs text-amber-600">
              <AlertTriangle className="h-3.5 w-3.5" /> The domain&apos;s products changed since this
              was generated — regenerate to refresh.
            </div>
          )}
          {domainAnalysis && !domainAnalysis.llm_used && (
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Info className="h-3.5 w-3.5" /> Heuristic analysis (no Foundation Model endpoint
              configured) — connect an LLM endpoint for a domain-expert pass.
            </div>
          )}
          {!domainAnalysis && (
            <p className="text-sm text-muted-foreground">
              Click &quot;Generate analysis&quot; to produce ROI-ranked use cases and a data-gap
              analysis for this domain.
            </p>
          )}
        </CardContent>
      </Card>

      {domainAnalysis && (
        <>
          {domainAnalysis.flagship?.use_case && (
            <Card className="shadow-sm border-primary/40">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                  <Star className="h-4 w-4 text-amber-500" /> Recommended flagship:{' '}
                  {domainAnalysis.flagship.use_case}
                </CardTitle>
                <CardDescription>{domainAnalysis.flagship.rationale}</CardDescription>
              </CardHeader>
            </Card>
          )}

          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Use cases (ranked by ROI)</CardTitle>
              <CardDescription>
                Ranked High → Low with the value driver, data readiness, effort, and time-to-value.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {domainAnalysis.use_cases.length === 0 ? (
                <p className="text-sm text-muted-foreground">No use cases produced.</p>
              ) : (
                <div className="overflow-x-auto">
                  <Table className="min-w-[1150px] table-fixed">
                    <TableHeader>
                      <TableRow>
                        <TableHead className="w-[24%]">Use case</TableHead>
                        <TableHead className="w-[80px]">ROI</TableHead>
                        <TableHead className="w-[90px]">Opportunity</TableHead>
                        <TableHead className="w-[22%]">Value driver</TableHead>
                        <TableHead className="w-[16%]">Data readiness</TableHead>
                        <TableHead className="w-[70px]">Effort</TableHead>
                        <TableHead className="w-[90px]">Time to value</TableHead>
                        <TableHead className="w-[14%]">Products</TableHead>
                        <TableHead className="w-[150px]">Data product</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {[...domainAnalysis.use_cases]
                        .sort((a, b) => displayScore(b) - displayScore(a))
                        .map((u, i) => (
                        <TableRow key={`${u.title}-${i}`} className="align-top">
                          <TableCell className="font-medium align-top whitespace-normal break-words py-3">
                            {u.title}
                            {u.description && (
                              <div className="text-xs text-muted-foreground font-normal mt-1 whitespace-normal break-words">
                                {u.description}
                              </div>
                            )}
                          </TableCell>
                          <TableCell className="align-top py-3">
                            <Badge className={`text-[10px] ${ROI_BADGE[u.roi_tier] ?? ''}`}>
                              {u.roi_tier}
                            </Badge>
                          </TableCell>
                          <TableCell className="align-top py-3">
                            <div className="flex items-center gap-2">
                              <span className="text-sm font-semibold tabular-nums">
                                {displayScore(u)}
                              </span>
                              <div className="h-1.5 flex-1 rounded-full bg-muted overflow-hidden">
                                <div
                                  className="h-full bg-primary"
                                  style={{ width: `${Math.max(0, Math.min(100, displayScore(u)))}%` }}
                                />
                              </div>
                            </div>
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground align-top whitespace-normal break-words py-3">
                            {u.value_driver}
                          </TableCell>
                          <TableCell className="text-xs text-muted-foreground align-top whitespace-normal break-words py-3">
                            {u.data_readiness}
                          </TableCell>
                          <TableCell className="text-xs align-top py-3">{u.effort}</TableCell>
                          <TableCell className="text-xs align-top py-3">{u.time_to_value}</TableCell>
                          <TableCell className="text-xs text-muted-foreground align-top whitespace-normal break-words py-3">
                            {(u.products ?? []).join(', ')}
                          </TableCell>
                          <TableCell className="align-top py-3">
                            {draftedTitles.has(u.title) ? (
                              <Button
                                size="sm"
                                variant="ghost"
                                className="h-7 gap-1 px-2 text-xs text-emerald-600"
                                onClick={() => void navigate('/data-product-drafts')}
                              >
                                <Check className="h-3.5 w-3.5" /> View draft
                              </Button>
                            ) : (
                              <Button
                                size="sm"
                                variant="outline"
                                className="h-7 gap-1 px-2 text-xs"
                                disabled={describingTitle === u.title}
                                title="Describe this use case as a data product (staged separately)"
                                onClick={() => void describe(u)}
                              >
                                {describingTitle === u.title ? (
                                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                                ) : (
                                  <Package className="h-3.5 w-3.5" />
                                )}
                                Describe
                              </Button>
                            )}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Data gaps</CardTitle>
              <CardDescription>
                Missing or weak data a domain expert would flag as needed for these use cases.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {domainAnalysis.data_gaps.length === 0 ? (
                <p className="text-sm text-muted-foreground">No data gaps identified.</p>
              ) : (
                domainAnalysis.data_gaps.map((g, i) => (
                  <div key={`${g.gap}-${i}`} className="rounded-lg border p-3 space-y-1">
                    <div className="flex items-center gap-2">
                      <Badge variant={SEV_BADGE[g.severity] ?? 'outline'} className="text-[10px]">
                        {g.severity}
                      </Badge>
                      <span className="font-medium text-sm">{g.gap}</span>
                    </div>
                    <p className="text-xs text-muted-foreground">{g.why_it_matters}</p>
                    {(g.unblocks ?? []).length > 0 && (
                      <p className="text-xs text-muted-foreground flex items-center gap-1">
                        <ArrowRight className="h-3 w-3" /> Unblocks: {g.unblocks.join(', ')}
                      </p>
                    )}
                  </div>
                ))
              )}
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
