// Domain Analysis — a ROI-ranked set of use cases + a data-gap analysis for the
// SELECTED domain (all its products). Generated by the LLM (grounded in the
// domain's products/DDL/KPIs, with a deterministic fallback), persisted in
// Lakebase, and loaded back; regenerable with a staleness indicator. Scope comes
// from the left-panel Domain selection (ALL domains → whole catalog).
import { useState } from 'react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
  Badge,
  Button,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@databricks/appkit-ui/react';
import { Sparkles, Loader2, AlertTriangle, Star, ArrowRight, RefreshCw, Info } from 'lucide-react';
import { useProduct } from '../lib/product';
import type { RoiTier, GapSeverity } from '../lib/domainAnalysis';

const ROI_BADGE: Record<RoiTier, string> = {
  High: 'bg-emerald-600 text-white',
  Medium: 'bg-amber-500 text-white',
  Low: 'bg-muted text-muted-foreground',
};
const SEV_BADGE: Record<GapSeverity, 'destructive' | 'default' | 'outline'> = {
  Critical: 'destructive',
  Important: 'default',
  'Nice-to-have': 'outline',
};

export function DomainAnalysis() {
  const {
    domainAnalysis,
    domainAnalysisStale,
    domainAnalyzing,
    domainAnalysisLabel,
    regenerateDomainAnalysis,
  } = useProduct();
  const [note, setNote] = useState<string | null>(null);

  const run = async () => {
    setNote(null);
    const r = await regenerateDomainAnalysis();
    if (!r.ok) setNote(`Generation failed: ${r.error ?? 'unknown error'}`);
    else if (r.persist_warning) setNote(`Generated, but not persisted: ${r.persist_warning}`);
  };

  return (
    <div className="space-y-4">
      <Card className="shadow-sm">
        <CardHeader className="flex flex-row items-center justify-between gap-4">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" /> Domain Analysis — {domainAnalysisLabel}
            </CardTitle>
            <CardDescription>
              ROI-ranked use cases and a data-gap analysis across all products in this domain,
              grounded in the schema and enriched with domain expertise.
            </CardDescription>
          </div>
          <Button size="sm" className="gap-1.5 shrink-0" disabled={domainAnalyzing} onClick={() => void run()}>
            {domainAnalyzing ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : domainAnalysis ? (
              <RefreshCw className="h-4 w-4" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
            {domainAnalysis ? 'Regenerate' : 'Generate analysis'}
          </Button>
        </CardHeader>
        <CardContent className="space-y-2">
          {note && <p className="text-sm text-destructive">{note}</p>}
          {domainAnalysis && domainAnalysisStale && (
            <div className="flex items-center gap-1.5 text-xs text-amber-600">
              <AlertTriangle className="h-3.5 w-3.5" /> The domain&apos;s products changed since this
              was generated — regenerate to refresh.
            </div>
          )}
          {domainAnalysis && !domainAnalysis.llm_used && (
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Info className="h-3.5 w-3.5" /> Heuristic analysis (no Foundation Model endpoint
              configured) — connect an LLM endpoint for a domain-expert pass.
            </div>
          )}
          {!domainAnalysis && (
            <p className="text-sm text-muted-foreground">
              Click &quot;Generate analysis&quot; to produce ROI-ranked use cases and a data-gap
              analysis for this domain.
            </p>
          )}
        </CardContent>
      </Card>

      {domainAnalysis && (
        <>
          {domainAnalysis.flagship?.use_case && (
            <Card className="shadow-sm border-primary/40">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                  <Star className="h-4 w-4 text-amber-500" /> Recommended flagship:{' '}
                  {domainAnalysis.flagship.use_case}
                </CardTitle>
                <CardDescription>{domainAnalysis.flagship.rationale}</CardDescription>
              </CardHeader>
            </Card>
          )}

          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Use cases (ranked by ROI)</CardTitle>
              <CardDescription>
                Ranked High → Low with the value driver, data readiness, effort, and time-to-value.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {domainAnalysis.use_cases.length === 0 ? (
                <p className="text-sm text-muted-foreground">No use cases produced.</p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Use case</TableHead>
                      <TableHead>ROI</TableHead>
                      <TableHead>Value driver</TableHead>
                      <TableHead>Data readiness</TableHead>
                      <TableHead>Effort</TableHead>
                      <TableHead>Time to value</TableHead>
                      <TableHead>Products</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {domainAnalysis.use_cases.map((u, i) => (
                      <TableRow key={`${u.title}-${i}`}>
                        <TableCell className="font-medium">
                          {u.title}
                          {u.description && (
                            <div className="text-xs text-muted-foreground font-normal mt-0.5">
                              {u.description}
                            </div>
                          )}
                        </TableCell>
                        <TableCell>
                          <Badge className={`text-[10px] ${ROI_BADGE[u.roi_tier] ?? ''}`}>
                            {u.roi_tier}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-xs text-muted-foreground max-w-[220px]">
                          {u.value_driver}
                        </TableCell>
                        <TableCell className="text-xs text-muted-foreground">{u.data_readiness}</TableCell>
                        <TableCell className="text-xs">{u.effort}</TableCell>
                        <TableCell className="text-xs">{u.time_to_value}</TableCell>
                        <TableCell className="text-xs text-muted-foreground">
                          {(u.products ?? []).join(', ')}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>

          <Card className="shadow-sm">
            <CardHeader>
              <CardTitle>Data gaps</CardTitle>
              <CardDescription>
                Missing or weak data a domain expert would flag as needed for these use cases.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {domainAnalysis.data_gaps.length === 0 ? (
                <p className="text-sm text-muted-foreground">No data gaps identified.</p>
              ) : (
                domainAnalysis.data_gaps.map((g, i) => (
                  <div key={`${g.gap}-${i}`} className="rounded-lg border p-3 space-y-1">
                    <div className="flex items-center gap-2">
                      <Badge variant={SEV_BADGE[g.severity] ?? 'outline'} className="text-[10px]">
                        {g.severity}
                      </Badge>
                      <span className="font-medium text-sm">{g.gap}</span>
                    </div>
                    <p className="text-xs text-muted-foreground">{g.why_it_matters}</p>
                    {(g.unblocks ?? []).length > 0 && (
                      <p className="text-xs text-muted-foreground flex items-center gap-1">
                        <ArrowRight className="h-3 w-3" /> Unblocks: {g.unblocks.join(', ')}
                      </p>
                    )}
                  </div>
                ))
              )}
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}
