// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    daily_trend: {
        name: "daily_trend";
        parameters: {
          /** STRING - use sql.string() */
          regions: SQLStringMarker;
          /** STRING - use sql.string() */
          states: SQLStringMarker;
          /** STRING - use sql.string() */
          stores: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          calendar_day: string;
          /** @sqlType BIGINT */
          total_customers: number;
          /** @sqlType DECIMAL(38,12) */
          labor_cost_per_customer: number;
          /** @sqlType DECIMAL(38,12) */
          labor_hours_per_customer: number;
          /** @sqlType DECIMAL(38,14) */
          dual_customer_conversion_rate_pct: number;
        }>;
      };
    filter_options: {
        name: "filter_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          kind: string;
          /** @sqlType STRING */
          value: string;
          /** @sqlType STRING */
          label: string;
        }>;
      };
    kpi_summary: {
        name: "kpi_summary";
        parameters: {
          /** STRING - use sql.string() */
          regions: SQLStringMarker;
          /** STRING - use sql.string() */
          states: SQLStringMarker;
          /** STRING - use sql.string() */
          stores: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          total_customers: number;
          /** @sqlType DECIMAL(28,2) */
          total_labor_cost: number;
          /** @sqlType DECIMAL(28,2) */
          total_labor_hours: number;
          /** @sqlType BIGINT */
          dual_customers: number;
          /** @sqlType DECIMAL(38,12) */
          labor_cost_per_customer: number;
          /** @sqlType DECIMAL(38,12) */
          labor_hours_per_customer: number;
          /** @sqlType DECIMAL(38,14) */
          dual_customer_conversion_rate_pct: number;
          /** @sqlType BIGINT */
          store_count: number;
          /** @sqlType BIGINT */
          day_count: number;
        }>;
      };
    opportunities: {
        name: "opportunities";
        parameters: {
          /** STRING - use sql.string() */
          regions: SQLStringMarker;
          /** STRING - use sql.string() */
          states: SQLStringMarker;
          /** STRING - use sql.string() */
          stores: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          opportunity_rank: number;
          /** @sqlType INT */
          store_number: number;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region_name: string;
          /** @sqlType DECIMAL(18,4) */
          labor_cost_per_customer: number;
          /** @sqlType DECIMAL(18,4) */
          benchmark_lcpc: number;
          /** @sqlType DECIMAL(18,4) */
          lcpc_gap: number;
          /** @sqlType DECIMAL(18,2) */
          opportunity_usd: number;
          /** @sqlType STRING */
          opportunity_flag: string;
        }>;
      };
    product_registry: {
        name: "product_registry";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType STRING */
          display_name: string;
          /** @sqlType STRING */
          domain: string;
          /** @sqlType STRING */
          business_outcome: string;
          /** @sqlType STRING */
          serving_object_name: string;
          /** @sqlType STRING */
          ontology_status: string;
          /** @sqlType STRING */
          contract_status: string;
          /** @sqlType BOOLEAN */
          app_enabled: boolean;
          /** @sqlType STRING */
          owner: string;
          /** @sqlType STRING */
          tags: string;
        }>;
      };
    store_diagnostics: {
        name: "store_diagnostics";
        parameters: {
          /** STRING - use sql.string() */
          regions: SQLStringMarker;
          /** STRING - use sql.string() */
          states: SQLStringMarker;
          /** STRING - use sql.string() */
          stores: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          store_number: number;
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          region_name: string;
          /** @sqlType STRING */
          state_code: string;
          /** @sqlType BIGINT */
          active_days: number;
          /** @sqlType BIGINT */
          total_customers: number;
          /** @sqlType DECIMAL(18,2) */
          avg_daily_customers: number;
          /** @sqlType DECIMAL(18,4) */
          labor_cost_per_customer: number;
          /** @sqlType DECIMAL(18,4) */
          labor_hours_per_customer: number;
          /** @sqlType DECIMAL(18,2) */
          dual_customer_conversion_rate_pct: number;
        }>;
      };
  }
}
