-- =============================================================================
-- jai_seed_demo_layer  (SYNTHETIC DEMO SEED — store-day base measures)
-- Target: jai_ontos.demo_schema   |  Warehouse: bf7ffcda00a8c351 (jai-sql-warehouse)
--
-- WHY THIS EXISTS: the runbook reference catalog `fc_entdata_gold` is NOT
-- reachable from jai_classic_ws, and jai_ontos.rt_str_lbr is empty. Per the
-- runbook fallback ("if the local schema lacks usable data, create a minimal
-- seeded demo layer"), we materialize a LABELED SYNTHETIC base table here and
-- build the governed jai_ serving views on top (sql/01b, 02, 03, 04).
--
-- This is DEMO DATA ONLY, clearly named *_synthetic_*, kept separate from any
-- real governed source. Generated by app/seed/generate_seed.py.
--
-- LOAD STEPS (run once):
--   1. python app/seed/generate_seed.py
--   2. databricks fs cp app/seed/store_day.parquet \
--        dbfs:/Volumes/jai_ontos/demo_schema/jai_seed_files/store_day.parquet \
--        -p jai-classic --overwrite
--   3. run this file, then 01b -> 02 -> 03 -> 04
-- =============================================================================

CREATE VOLUME IF NOT EXISTS jai_ontos.demo_schema.jai_seed_files
  COMMENT 'Synthetic demo seed files for RT_onto_demo';

CREATE OR REPLACE TABLE jai_ontos.demo_schema.jai_synthetic_store_day_seed
COMMENT 'SYNTHETIC DEMO DATA — store-day base measures for RT_onto. Not governed source.'
AS SELECT
  CAST(store_number AS INT)              AS store_number,
  CAST(store_name AS STRING)            AS store_name,
  CAST(store_city AS STRING)            AS store_city,
  CAST(state_code AS STRING)            AS state_code,
  CAST(region_name AS STRING)           AS region_name,
  CAST(store_status AS STRING)          AS store_status,
  CAST(date_key AS INT)                 AS date_key,
  CAST(calendar_day AS DATE)            AS calendar_day,
  CAST(total_customers AS BIGINT)       AS total_customers,
  CAST(shop_customers AS BIGINT)        AS shop_customers,
  CAST(fuel_customers AS BIGINT)        AS fuel_customers,
  CAST(dual_customers AS BIGINT)        AS dual_customers,
  CAST(total_labor_hours AS DECIMAL(18,2)) AS total_labor_hours,
  CAST(total_labor_cost AS DECIMAL(18,2))  AS total_labor_cost
FROM read_files(
  '/Volumes/jai_ontos/demo_schema/jai_seed_files/store_day.parquet',
  format => 'parquet'
);
